name: Node CI

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - '*'

permissions:
    contents: read

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]
                node-version: [18.15.0]
        runs-on: ${{ matrix.platform }}
        env:
            PUPPETEER_SKIP_DOWNLOAD: true
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.32.9
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: false
                  cache: 'pnpm'

            - run: npm i -g pnpm

            - run: pnpm install

            - run: pnpm lint

            - run: pnpm build
             # locate the pnpm store directory where pnpm dependencies are installed
            - name: Get pnpm store directory
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
              # Cypress github-action does not cache pnpm dependencies by default.
              # Cache the dependencies.
            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                path: ${{ env.STORE_PATH }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('examples/basic-pnpm/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-store-
            - name: Install dependencies
              # with Cypress GitHub Action.
              # Calling the Cypress GitHub Action causes all dependencies from
              # the root of the pnpm workspace to be installed
              # AND it automatically caches the Cypress binary.
              #
              # If you copy this workflow to another repository replace the following with
              # uses: cypress-io/github-action@v6
              # The notation ./ is a special usage only used here.
              # It causes the version of the action code from whatever branch it is launched in to be used.
              # Do not try to use the ./ notation this outside of this repository!
              uses: ./ # approximately equivalent to using cypress-io/github-action@v6
              with:
                working-directory: examples/start-and-pnpm-workspaces
                runTests: false
            - name: Cypress test Single
              # Run Cypress in examples/start-and-pnpm-workspaces/packages/workspace-1 only
              uses: ./ # equivalent to using cypress-io/github-action@v6
              with:
                # Do not attempt to install dependencies in the workspace using the action.
                # There is no pnpm-lock.yaml file in a workspace for
                # Cypress GitHub Action to use.
                # We already installed dependencies when we called the action previously.
                install: false
                working-directory: packages/server
                build: pnpm run build
                start: pnpm start
                wait-on: 'http://localhost:3000'
